CFLAGS ?= -g -O0 -fno-omit-frame-pointer -Wall -Wextra -no-pie
TARGETS=prog1 fork multithread testprog anti-ptrace loop loop_syscall

.PHONY: build
build: $(TARGETS)

.PHONY: clean
clean:
	rm -f $(TARGETS)

